### ISSUE TITLE
Error occurs when running fn.metaSIM

### ISSUE THREAD

**Issue by mdonald** [sokole/MCSim#1]
Hello! I'm very excited about the MCSim package. However, as I was working through the tutorial I received an error message when running fn.metaSIM. The error is:
**Error in SWM %*% as.matrix(J.t.minus.1.RAs) : 
  requires numeric/complex matrix/vector arguments**
 
In looking at the underlying code, I think it pertains to the section copied below. Do you have a suggestion for how to resolve the error to run the tutorial? 
%# calculate I for each site based on composition of neighboring sites
  I.RAs<-SWM%*%as.matrix(J.t.minus.1.RAs) #distance decay without species bias

Full code that I've used and error message pasted below:
 %#set	random	seed
 set.seed(1234)
 %#	make a landscape
xy.coordinates <- data.frame( x = c(1, 2, 3, 4, 5), y = c(1, 3, 1, 5, 2))
 my.landscape	<- MCSim::fn.make.landscape(
 site.coords = xy.coordinates,
  m	= 0.5,
  JM	= 1000000)
[1] "gangsta"
%# niche	positions,	niche	breadths,	and	relative	abundances	for	three	species
 niche.positions	<-		c(-.5,	0,	.5)
 niche.breadths	<- c(.2,	.2,	5)
 regional.rel.abund	<- c(.8,	.1,	.1)
 %# run	a	simulation	with	10	generations
 sim.result <- MCSim::fn.metaSIM(
  landscape = my.landscape,
  trait.Ef = niche.positions,
  trait.Ef.sd = niche.breadths,	
  gamma.abund = regional.rel.abund,
  W.r	= 0,
  nu	= 0.001,
  n.timestep	= 10,	
  sim.ID	= "my_test_sim",
  output.dir.path	= "my_sim_output_directory"
)
**Error in SWM %*% as.matrix(J.t.minus.1.RAs) : 
  requires numeric/complex matrix/vector arguments**

**Comment by sokole** [comment]
@mdonald  Thanks for the message. This bug just started to show up this summer and I think it has to do with an update to R or one of the packages MCSim depends upon.  I was going to fix it in the next major update to MCSim, but it seems it's broken the package all together, so I'll try to do a minor release with a fix for this bug soon. Thanks!

**Comment by mdonald** [comment]
Thanks for the quick response! Looking forward to the new mini-release. Until then, would you suggest using a previous version of R with this package?

**Comment by sokole** [comment]
I haven't had a chance to diagnose it yet, so I'm not 100% sure. But I would give it a try with a version of R that predates May of this year, or earlier. If you get a chance to try that, please let me know if it works.

**Comment by mdonald** [comment]
The package works on R version 3.4.4! (It does kick a warning message that summarize_each() is depreciated.) Thanks for the quick responses.

**Comment by sokole** [comment]
re-opening... will fix so that MCSim works with newer versions of R
- [ ] make work with newer versions of R (> 3.4.4)
- [ ] fix warning message that summarize_each() is depreciated.

**Comment by mdonald** [comment]
Great, thank you! Looking forward to the updated version.
